### PR TITLE
Small positive adaptations I needed on my branch

### PR DESCRIPTION
**Pull request by Kequc**

### CODE REVIEW

**Comment by chris-rudmin** [comment]
Thanks for the PR. I like the fix for getTracks and good idea for raw data instead of blob.
Could you add info for the config into the Readme?

Also i'm a bit nervous about adding a new event into the audioProcessing node as I don't want this loop to take too long. I'm actually considering removing the `duration` event. For visualizers and the like, I think it would be better to create a new AudioContext in which you are in control of your own elements.

**Comment by Kequc** [comment]
I don't use the duration event. It's more effective to track the duration outside of this library, by setting a start time and using subtraction. Or perhaps there could be a public variable or function in the library that returns it.

Hmm, I'm not sure about your suggestion regarding channel data. I wasn't able to find a better method of exposing that data. Are you suggesting a separate audio listener, run separately outside of the library?

I didn't realise that returning these events was cpu intensive. If they are, perhaps the duration event could be removed or replaced. Having audio visualisations based on channel data is highly useful for me, but maybe it's not such an important feature.

**Comment by chris-rudmin** [comment]
It's not the events that are CPU intensive, it is what is done when the event is received which *could* be intensive. These event publishes are actually synchronous, so if something intensive is done, it could interfere with the audio stream.

**Comment by Kequc** [comment]
A feature I'd love to see and am considering adding is support for cross domain web workers through use of XMLHTTPRequest and createObjectUrl. Do you think that would be a useful addition to the library, will there be friction with regard to use of importScripts used at the top of oggopusEncoder?

At the current time it is not possible to use this library in conjunction with a CDN.

Unfortunately this isn't a widely discussed topic and information about exactly what needs to happen is sparse. What do you think.

http://colonelpanic.net/2014/08/using-pdf-js-web-worker-cross-domain-cors/

**Comment by chris-rudmin** [comment]
@Kequc It's not quite clear to me what the use case is for cross domain web worker? Can you explain in a bit more detail what you want to do, and why it doesn't work?

**Comment by Kequc** [comment]
Web workers currently do not work cross-origin in, I believe, any prominent browsers. That means if the oggopusEncoder is instantiated as a worker but is hosted on a different domain than the currently open webpage it will not work. This is terrible for CDNs, then.

You will receive the following errors:

`Uncaught SecurityError: Failed to construct 'Worker': Script at 'http:otherdomain.co/worker.js' cannot be accessed from origin`

or: `[Error] SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent`

or: `SecurityError: The operation is insecure.`

I'm writing a client side sdk which makes use of this library, and in order for it to work my clients each need to host these files on their own domain.

**Comment by Kequc** [comment]
There is a known workaround to this issue in the form of loading the worker script using ajax, populates a blob. Then assigning the blob to a objecturl, which the Worker can then load. This essentially makes the url local. Otherwise known as "inlining" the worker.

(untested psudo code)
```javascript
function getWorkerUrl (url, next) {
  var xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function () {
    if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
      var workerJSBlob = new Blob([xmlhttp.responseText], {
          type: "text/javascript"
      });
      next(window.URL.createObjectURL(workerJSBlob));
    }
  };
  xmlhttp.open("GET", url, true);
  xmlhttp.send();
}

getWorkerUrl('//otherdomain.co/worker.js', function (url) {
  var worker = new Worker(url);
});
```

**Comment by chris-rudmin** [comment]
Seems a little bit hacky, and not something I would want to merge. Does it
work with importscript calls inside of the worker?

**Comment by Kequc** [comment]
That's what I'm seeing is that it doesn't work with importScripts. I was just reading about that now. It's also unreliable to assume importScripts works cross-origin too. I'd have to fork the whole repository I think, in order to encompass it in an app that compiles the files together.

sigh

Thanks for hearing me.

**Comment by Kequc** [comment]
This thread is starting to get a little bit unwieldy. I'm sorry about that, on yet another of my separate topics... could you tell me what these three lines of the application do?

https://github.com/chris-rudmin/Recorderjs/blob/master/recorder.js#L166-L169

**Comment by chris-rudmin** [comment]
@Kequc When starting a second recording session, the first data buffers received contain the audio from the end of the last session. These lines of code override the encode prototype with an instance method. When it gets executed (first time only) it deletes itself and then the recorder calls the encode as defined by the prototype.

**Comment by chris-rudmin** [comment]
It's more efficient than doing a variable check every iteration of the processAudioNode

**Comment by chris-rudmin** [comment]
FYI In the speex branch, i've taken some of your ideas here (fix for stopTracks and returning raw buffers) and incorporated it. I'll try a merge this into speex and see what happens.

**Comment by chris-rudmin** [comment]
Closing PR, I've merged fixes into speexdsp branch which will go to master!  Thanks!

**Pull request closed without merging**
